import Layout from "../components/Layout";

export default function Home() {
  return (
    <Layout title="Home">
      <p className="text-4xl">Welcome to Nextjs</p>
    </Layout>
    // <div className="min-h-screeen py-0 px-2 flex flex-col justify-center items-center">
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <h1>Hello Nextjs</h1>
    // </div>
  );
}
